### ISSUE TITLE
Symfony config + HttpClient gives "Invalid transport"

### ISSUE THREAD

**Issue by jmsche** [jolicode/elastically#139]
Hi,

I'm currently testing the new Symfony bundle, and I'm facing this issue when trying to index data:

```
In AbstractTransport.php line 129:
                                         
  [Elastica\Exception\InvalidException]  
  Invalid transport 
```

When I dump() the $transport before the if() statement, I get a string instead of a service:
`@JoliCode\Elastically\Transport\HttpClientTransport`

Here is my (truncated) Elastically config:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    JoliCode\Elastically\Messenger\DocumentExchangerInterface:
        alias: App\Elasticsearch\DocumentExchanger

    JoliCode\Elastically\Transport\HttpClientTransport: ~

elastically:
    connections:
        default:
            client:
                host: '%env(ELASTICSEARCH_HOST)%'
                port: '%env(ELASTICSEARCH_PORT)%'
                transport: '@JoliCode\Elastically\Transport\HttpClientTransport'
            mapping_directory: '%kernel.project_dir%/config/elasticsearch'
            bulk_size: 100
            prefix: formations_%kernel.environment%
            index_class_mapping:
                sector: App\Elasticsearch\Model\Sector

framework:
    messenger:
        transports:
            sync: 'sync://'
        routing:
            'JoliCode\Elastically\Messenger\IndexationRequest': sync
```

Did I miss something?
