### ISSUE TITLE
Decorate IndexBuilder

### ISSUE THREAD

**Issue by orangevinz** [jolicode/elastically#185]
Thanks for Elastically !

As I'd like to implement my own pattern for indice names (in place of `date('Y-m-d-His')`), so I guess decorating `IndexBuilder` is the 
 right way to do that.
But injected arguments are private and don't have getters, which obliges me to re-declare constructor.
Would it be a good idea to add getters in the IndexBuilder class ?
I can write a PR if you estimate that's the good practice.

To be able to do 
```php
#[AsDecorator(decorates: IndexBuilder::class)]
class IndexBuilderDecorator
{
    public function __construct(
        #[AutowireDecorated]
        private object $inner,
    ) {}

    public function createIndex(string $indexName, array $context = []): Index
    {
        // $this->inner->getMappingProvider();
    }
}
```

Instead of 
```yaml
    App\Search\IndexBuilderDecorator:
        class: App\Search\IndexBuilderDecorator
        decorates: 'JoliCode\Elastically\IndexBuilder'
        arguments:
            - '@.inner'
            - '@elastically.default.mapping.provider'
            - '@elastically.default.client'
            - '@elastically.default.index_name_mapper'
        decoration_inner_name: 'JoliCode\Elastically\IndexBuilder.inner'
```
```php
class IndexBuilderDecorator
{
    public function __construct(
        private IndexBuilder $inner,
        private MappingProviderInterface $mappingProvider,
        private Client $client,
        private IndexNameMapper $indexNameMapper
    ) {}

    public function createIndex(string $indexName, array $context = []): Index
    {
        // $this->mappingProvider
    }
}
```
