### ISSUE TITLE
array of nested objects not transformed to objects

### ISSUE THREAD

**Issue by bogdandubyk** [jolicode/elastically#88]
so if I have a dto like 

```
final class SomeDto {

   /**
     * @param int $id
     * @param string $name
     * @param SeconfDto $secondDto
     * @param array<ThirdDto> $otherDtos
     */
    public function __construct(publid int $id, public string $name, public SeconfDto $secondDto, public array $otherDtos) {
    }
}
```
and retrieving it from the elastic search using  `$index->getModel(1);` it's not converting `$otherDtos` to instances of `ThirdDto`, but simply return as an array of associative arrays. 

Here is the mapping file:

```
mappings:
    dynamic: false
    properties:
        name:
            type: text
            analyzer: english
            fields:
                autocomplete:
                    type: text
                    analyzer: app_autocomplete
                    search_analyzer: standard
        secondDto:
            type: object
            properties:
                name:
                    type: text
                    analyzer: english
                    fields:
                        autocomplete:
                            type: text
                            analyzer: app_autocomplete
                            search_analyzer: standard
        otherDtos:
            type: object
            properties:
                name:
                    type: text
                    analyzer: english
                    fields:
                        autocomplete:
                            type: text
                            analyzer: app_autocomplete
                            search_analyzer: standard
```
Is this not supported to use nested dto's, or maybe I'm doing something wrong?????
